#!/bin/sh

cd "$(dirname "$0")/.."

CONFIG_SCRIPT="./script/_config"
test -r ${CONFIG_SCRIPT} && . ${CONFIG_SCRIPT}

TYPE_PARAM="$1"
RELEASE_PARAM="$2"
CONNECTEDHOMEIP_DIR=${IOTER_DIR}"/third_party/ioter-stable"
OUTPUT=${CONNECTEDHOMEIP_DIR}"/out/linux-x64-all-clusters-asan-clang-${TYPE_PARAM}/chip-all-clusters-app"

HELP_STR="Please, use build_ioter with following options.
./script/build_ioter fed
./script/build_ioter med
./script/build_ioter sed"

install_chip_all_clusters_app()
{
    # for release
    if [ "-r" = "${RELEASE_PARAM}" ]; then
        LOCAL_BUILD=""
    fi

    INSTALL_NAME=${IOTER_BIN_DIR}"/chip-all-clusters-app${LOCAL_BUILD}-${TYPE_PARAM}"
    echo "install chip-all-clusters-app to ${INSTALL_NAME}"
    cp ${OUTPUT} ${INSTALL_NAME}
}

build_chip_all_clusters_app()
{
    cd "${CONNECTEDHOMEIP_DIR}"
    . scripts/activate.sh

    if [ "-r" = "${RELEASE_PARAM}" ]; then
        rm -rf out/linux-x64-all-clusters-asan-clang-${TYPE_PARAM}
    fi

    ./scripts/run_in_build_env.sh "./scripts/build/build_examples.py --target linux-x64-all-clusters-asan-clang-${TYPE_PARAM} build"
    if [ $? -eq 0 ];then
        echo "chip-all-clusters-app is generated"
        echo "output : ${OUTPUT}"
        install_chip_all_clusters_app
    fi
}

main()
{
    if [ "fed" = "$TYPE_PARAM" ] || [ "med" = "$TYPE_PARAM" ] || [ "sed" = "$TYPE_PARAM" ]; then
        build_chip_all_clusters_app
    else
        echo "build_ioter : invalid option ${TYPE_PARAM}"
        echo "${HELP_STR}"
    fi
}

main
