#!/bin/bash

cd "$(dirname "$0")/.."

CONFIG_SCRIPT="./script/_config"
test -r ${CONFIG_SCRIPT} && . ${CONFIG_SCRIPT}

RELEASE_PARAM="$1"
DEVICE_TYPE=("fed" "med" "sed")
OPENTHREAD_DIR=${IOTER_DIR}"/third_party/openthread/ot-samsung"
OPENTHREAD_LIB_TYPE=("ftd" "mtd" "mtd")
OPENTHREAD_VER="1.3"

_install()
{
    i=0
    while [ ${i} -le 2 ]; do
        INSTALL_NAME=${IOTER_LIB_DIR}"/libopenthread.so.${OPENTHREAD_VER}-${DEVICE_TYPE[i]}${LOCAL_BUILD}"
        LIB_NAME=${OPENTHREAD_DIR}"/build/posix/src/posix/platform/libopenthread-${OPENTHREAD_LIB_TYPE[i]}-posix-multithread.so"
        cp ${LIB_NAME} ${INSTALL_NAME}
        i=$((${i}+1))

        echo "output  : ${LIB_NAME}"
        echo "install : ${INSTALL_NAME}"
    done
}

install_openthread()
{
    # for release
    if [ "-r" = "${RELEASE_PARAM}" ]; then
        LOCAL_BUILD=""
    fi

    _install
}

build_openthread()
{
    cd "${OPENTHREAD_DIR}"

    if [ "-r" = "${RELEASE_PARAM}" ]; then
        rm -rf build/
    fi

    ./script/cmake-build posix -DOT_MULTITHREAD=ON -DOT_PLATFORM_NETIF=ON
    if [ $? -eq 0 ];then
        echo "shared libraries are generated"
        install_openthread
    fi
}

main()
{
    build_openthread
}

main
