#!/bin/sh

kill_allprocess()
{
    main_pid=$(ps -ef | grep -e "[m]ain.py" | awk '$1 == "root" {print $2}')
    if [ -n "${main_pid}" ]; then
        echo "kill main.py : ${main_pid}"
        sudo kill -9 "$main_pid"
    fi

    start_pid=$(ps -ef | grep -e "[s]cript/start" | awk '$1 == "root" {print $2}')
    if [ -n "${start_pid}" ]; then
        echo "kill script/start : ${start_pid}"
        sudo kill -9 "$start_pid"
    fi

    echo "kill chip-all-clusters-app"
    sudo killall chip-all-clusters-app
}

# TODO
# remove_alldata()
# {
    
# }

main()
{
    kill_allprocess
}

main