#!/bin/sh

cd "$(dirname "$0")/.."

CONFIG_SCRIPT="./script/_config"
test -r ${CONFIG_SCRIPT} && . ${CONFIG_SCRIPT}

python3_install()
{
    sudo apt-get -y install python3 cmake
    sudo apt-get -y install git gcc g++ pkg-config libssl-dev libdbus-1-dev \
        libglib2.0-dev libavahi-client-dev ninja-build python3-venv python3-dev \
        python3-pip unzip libgirepository1.0-dev libcairo2-dev libreadline-dev
    sudo pip install pyQt5
    sudo pip install psutil
    sudo pip install qrcode
    sudo pip install pyudev
    sudo pip install androidviewclient
    sudo apt install libxcb-xinerama0
    sudo apt install python3-pyqt5.qtmultimedia
}

main()
{
    python3_install
}

main
